name: Pages

on:
  push:
    branches:
      - main # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.22.12
        uses: actions/setup-node@v2
        with:
          node-version: "12.22.12"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          token: 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
          repository-name: dengjinjun/dengjinjun.github.io
          branch: gh-pages
          folder: public
          commit-message: "${{ github.event.head_commit.message }} Updated By Github Actions"